spring:
  application:
    name: reference-data-service
    port: 8080
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reference-data-db
  rabbitmq:
    host: localhost
    port: 15672
    username: guest
    password: guest